### ISSUE TITLE
Create UI bundle for sommerfeld.io

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/website#42]
As a website owner, I want to elevate the presentation of my documentation and blog pages by incorporating visually appealing Antora UI bundles. Due to the lack extensive design skills, I aim to leverage an existing publicly available documentation design and apply it uniformly across my website's various sections.

Apply the  theme for Antora.

#### Design
- [x] Use simple design without any cards for the docs pages (https://appstack.bootlab.io/docs-introduction)
- [x] Add breadcrumbs and branch / version toggle and no  "edit this page" link
- [x] Update header links (top-right)
    - Github (Github  Logo with drop down to my personal projects and the sommerfeld-io organization)
    - DockerHub
    - Contact
- [x] Update Footer Links
    - Privacy
    - Terms of Service
    - Contact
- [x] Update Copyright in Footer
- [x] Rename elements in left navigation ("Pages" to "Documentation" and "Documentation" to the title of the Antora component)
- [x] Add padding-top to ToC when screen gets small (or even hide ToC-column alltogether)

#### Build UI Bundle
- [x] Create a UI bundle based on http://localhost:5353/custom-docs-layout-5.html / https://www.sommerfeld.io/appstack/custom-docs-layout-5.html
- [x] Ship all Fonts with the UI bundle, do not load anything from the internet (load fonts with npm and use a dedicated CSS file, include css file before dark.css) - see https://docs.antora.org/antora-ui-default/add-fonts
- [x] Enable FontAwesome Icons
- [x] sommerfeld-io/website#31
- [x] sommerfeld-io/website#32
- [x] sommerfeld-io/website#33
- [x] sommerfeld-io/website#34
- [x] sommerfeld-io/website#36
- [x] Implement Left Nav
- [x] Implement header navigation 
- [x] Implement footer navigation 
- [x] Implement Versions and Branches Switcher
- [x] Implement Breadcrumbs
- [x] Implement Edit this page Button
- [x] Implement dedicated page to list all projects and versions (use something similar to http://localhost:5353/docs-changelog.html or http://localhost:5353/docs-plugins.html)
- [x] Implement 404 page layout ... include projects list here as well (or at least a link to the "All projects" page)
- [x] Configure webserver to use `/docs/404.html` as 404 page
- [x] Add a Layout for terms, contact and privacy: no buttons below the title, always show main content, no docs-nav
- [x] Add styles to display the article content with correct fonts, design, spacing, etc.
- [x] Add styles for admonitions
- [x] Add a text style for an article's preamble
- [x] Implement ToC (maybe some mandatory CSS classes are needed for the JS to work)
- [x] ToC indentation
- [x] Add Development Guidelines as Preview-Content
- [x] Add a layout for blog posts
- [x] Add rewrite rules for contact and the other static sites, to avoid too many crazy urls inside the ui bundle ... Document this! 
- [x] Move the whole website-ui-bundle project into the website project ... To make sure everything originated from the same place
- [x] Add a dockerignore file to make sure the UI bundle source files are not copied into the website image
- [x] Copy the UI bundle-zip into the image. This way the playbooks can reference the ui bundle locally
- [x] Move this issue (and every other issue) to website-repo too
- [x] #45
- [x] Add Content to
    - [x] Contact page
    - [x] Terms page
    - [x] Privacy page
- [x] Release as `v0.3.0-beta.0`

#### Full page organization (everything inside the Docker image)
- [x] sommerfeld-io/website#37
- [x] sommerfeld-io/website#38

#### Additional tasks
- [ ] sommerfeld-io/website#39
- [x] sommerfeld-io/website#40
- [x] sommerfeld-io/website#41
- [ ] #44
- [x] Re-organize project docs
    - Navs for all projects (avoid to nest pages too deeply)
    - Make project names shorter where needed
    - Do no use real pages for "expand" nav entries
- [x] Support Gitpod
- [x] Update PlantUML color schemes
- [x] Delete website-ui-bundle repo
- [ ] #63
- [ ] #66
- [ ] sommerfeld-io/website#35
- [ ] #65
