### ISSUE TITLE
Generate SBOM for Github projects and Docker image, add as a release asset and extend Dockerfile docs (the generated adoc file)

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/website#47]
### Read
- [x] https://github.blog/2023-03-28-introducing-self-service-sboms

### Docker
- `docker run -it --rm docker/scout-cli sbom --format list sommerfeldio/website:latest`
- `docker run -it --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" docker/scout-cli sbom --output sbom.json sommerfeldio/website:latest`
- `docker run -it --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" docker/scout-cli sbom --format list --output sbom.txt sommerfeldio/website:latest`

### Github Repo
- https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28 -> `gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/sommerfeld-io/website/dependency-graph/sbom`

### Todo
- [x] Add the SBOM automatically to the docs
- [x] Add the `Dockerfile-sbom.json` (or whatever the default filename is) automatically next to the Dockerfile
- [x] Turn SBOM list into valid asciidoc
- [ ] Generate SBOMs for all Dockerfiles of a repo
- [ ] adopt for other repos as well
