### ISSUE TITLE
Update Docker Tag Names for Branches

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/website#52]
As a software engineer, I want to enhance our Docker image tagging process to provide more clarity and context about the branch from which a Docker image was built. Currently, all non-release builds are tagged as "main," which makes it impossible to identify the source branch.

- Main Branch Builds - When a Docker image is built from the main branch, the tag should remain as "main."
    - Released versions carry `:latest` and `:v1.2.3`
- Branch Builds - For builds from other branches, the Docker image should be tagged with the branch name.
    - Unstable `ci.yml` builds from `main` carry `:main`
    - Unstable `ci.yml` builds from other branches carry `:branch-BRANCH-NAME`
        - When a PR is merged, the  `:branch-BRANCH-NAME` tag is deleted from DockerHub

Releases still re-tag the `:main` version. The `ci.yml` workflow ensures there is always an up-to-date `:main` version because the workflow is triggered when a PR is merged into `main` and ensures there is a new `:main` version

By implementing this enhancement, we aim to streamline our Docker image management, providing a more informative and organized approach to tracking images based on their source branches.

### Todo
- [x] Update the "About the Tags" block for all Docker Images, etc.
    - [x] Write or Update the Docker Tag policy section in the docs of https://github.com/sommerfeld-io/dev-environment-config
- [x] Implement new tagging inside a branch
    - [ ] Maybe create a dedicated `cleanup-after-merge.yml` or similar. See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged and my question https://stackoverflow.com/questions/77480804/trigger-github-actions-workflow-when-a-pr-is-merged
    - [ ] Remove `:branch-BRANCH-NAME` image from DockerHub. See https://stackoverflow.com/questions/44209644/how-do-i-delete-a-docker-image-from-docker-hub-via-command-line
- [ ] Compare Docker images with Docker Scout (CVEs)
    - [ ] compare `:branch-BRANCH-NAME` to `latest`
    - [ ] compare `:branch-BRANCH-NAME` to `main`
- [ ] Roll out for all repos of this organization
    - [ ] website
    - [ ] dev-environment-config
    - [ ] semver
- [x] Update all workflows to use `main` instead of `edge`
    - [x] Update Docs
    - [x] Delete all `edge` tags from DockerHub

**Comment by sebastian-sommerfeld-io** [comment]
New focus: Only deploy tags from main branch! No other branches!
Releases are still done from main!
